on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '20' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: check dependencies
      run: |
        if grep "@definitelytyped/" yarn.lock; then
          echo ""
          echo "A package in this monorepo is depending on an older version of one of its siblings. \
        Ensure all '@definitelytyped/*' dependencies in package.json files use the version \
        listed in lerna.json to let lerna automatically keep them in sync."

          echo ""
          echo "yarn.lock"
          cat yarn.lock | grep -A 5 -n "@definitelytyped/"
          exit 1
        fi
    - name: install
      run: yarn install --frozen-lockfile
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
  check-parse-results:
    needs: build_and_test
    uses: ./.github/workflows/check-parse-results.yml
  publish_alpha:
    name: publish alpha release
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: fetch tags
      run: git fetch origin +refs/tags/*:refs/tags/*
    - name: configure git
      run: |
        git config user.email "typescriptbot@microsoft.com"
        git config user.name "TypeScript Bot"
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org
    - name: install
      run: yarn install --frozen-lockfile
    - name: format
      run: |
        yarn format
        if [ -n "`git status -s`" ]; then
          git commit -am "Format"
          git push
        fi
    - name: build
      run: yarn build
