name: Daily Open PR Sync

on:
  workflow_dispatch: ~
  schedule:
    - cron: '37 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - run: pnpm install
      - run: pnpm run build

      # Go through all open PRs and run the bot over them
      - run: node packages/mergebot/dist/run.js
        env:
          BOT_AUTH_TOKEN: ${{ secrets.TYPESCRIPT_BOT_TOKEN }}
