on:
  release:
    types: [created]
jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org
    - name: configure git
      run: |
        git config user.email "typescriptbot@microsoft.com"
        git config user.name "TypeScript Bot"
    - name: install
      run: yarn install
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
    - name: version
      run: |
        ref=${{ github.ref }} # refs/tags/v0.0.1
        tag=${ref:11} # 0.0.1
        yarn lerna version $tag --yes --no-git-tag-version --no-push
        git commit -am "v$tag"
        git tag -af v$tag -m v$tag
        git push && git push --tags -f
    - name: publish to npm
      run: yarn lerna publish from-git --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: trigger publisher deploy
      uses: peter-evans/repository-dispatch@v1.0.0
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: published
        